# fly.toml app configuration file generated for open-swarm on 2025-01-17T22:46:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'open-swarm'
primary_region = 'syd'

[build]
  image = 'mhand79/open-swarm'

[env]
  PORT = '8000'
  LOW_VRAM_MODE = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1 
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="sqlite_data"
  destination="/mnt/sqlite_data"

