# Generated by Django 4.2.18 on 2026-06-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0010_initial_chat_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("repository_url", models.URLField(blank=True)),
                ("source", models.CharField(default="github", max_length=50)),
                ("manifest_data", models.JSONField(blank=True, default=dict)),
                (
                    "code_template",
                    models.TextField(
                        blank=True, help_text="Blueprint source template only"
                    ),
                ),
                ("required_mcp_servers", models.JSONField(blank=True, default=list)),
                ("category", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "marketplace_blueprint",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("repository_url", models.URLField(blank=True)),
                ("source", models.CharField(default="github", max_length=50)),
                ("manifest_data", models.JSONField(blank=True, default=dict)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("blueprint", "Blueprint"),
                            ("mcp_config", "MCP Config"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_id", models.IntegerField()),
            ],
            options={
                "db_table": "marketplace_index",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MCPConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("repository_url", models.URLField(blank=True)),
                ("source", models.CharField(default="github", max_length=50)),
                ("manifest_data", models.JSONField(blank=True, default=dict)),
                (
                    "config_template",
                    models.TextField(
                        blank=True,
                        help_text="Template JSON/YAML only. Do not include secrets.",
                    ),
                ),
                ("server_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "marketplace_mcp_config",
                "ordering": ["-created_at"],
            },
        ),
    ]
