# Generated by Django 4.2.18 on 2025-02-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueprints_university", "0001_initial_with_channel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachingunit",
            name="channel_id",
            field=models.CharField(
                blank=True,
                help_text="Slack channel ID associated with this teaching unit (e.g., C123456).",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
