name: Publish to TestPyPI

on:
  push:
    branches: [ "refactor-wip" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish-testpypi:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/open-swarm/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine setuptools

      - name: Build package artifacts
        run: python -m build --sdist --wheel --outdir dist/

      - name: Validate package structure
        run: twine check dist/*

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          username: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          attestations: false
          twine-args: --verbose