name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      # 1. Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install uv using the official standalone installer
      - name: Install uv
        uses: astral-sh/setup-uv@v4

      # 3. Set up Python environment
      - name: Set up Python
        run: uv python install

      # 4. Install pytest and pytest-cov
      - name: Install pytest and plugins
        run: |
          uv run pip install pytest pytest-cov

      # 5. Run Pytest with Coverage
      - name: Run tests with coverage
        run: |
          uv run pytest --cov=open_swarm_mcp --cov-report=xml --cov-report=json --cov-report=html

      # 6. Upload Coverage Report as Artifact
      - name: Upload Coverage Report (XML)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-xml
          path: coverage.xml

      - name: Upload Coverage Report (HTML)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-html
          path: htmlcov/

      # 7. Upload Coverage to Codecov (Optional)
      - name: Upload coverage to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}  # Ensure this secret is set in your repository
