name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Node.js and npm
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          node -v
          npm -v

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir .[dev]
          # Install nemoguardrails without its dependencies
          pip install --no-cache-dir --no-deps nemoguardrails

      - name: Run tests
        run: pytest
        env:
          PYTHONPATH: ${{ github.workspace }}/src
