name: Publish to TestPyPI

on:
  push:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/open-swarm/

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install build tools
      - name: Install build tools
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install build wheel twine

      # Build package artifacts
      - name: Build package artifacts
        run: |
          source venv/bin/activate
          python -m build

      # Validate package structure
      - name: Validate package structure
        run: |
          source venv/bin/activate
          twine check dist/*

      # Publish to TestPyPI
      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          source venv/bin/activate
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
