name: Publish to TestPyPI

on:
  push:
    branches: [ "main" ]
  release:
    types: [ published ]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/open-swarm/

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build wheel twine
    
    - name: Set Package Version
      # Set the version dynamically or use a predefined version
      env:
        UV_DYNAMIC_VERSIONING_BYPASS: 0.1.1  # Replace with your desired version
      run: echo "Version set to $UV_DYNAMIC_VERSIONING_BYPASS"
    
    - name: Build package artifacts
      run: python -m build
    
    - name: Validate package structure
      run: twine check dist/*
    
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        attestations: false
        twine-args: --verbose
